import "./globals.scss";
import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import ThemeProvider from "@/utils/useContext/themeChange/themeChangeContext";
import Layout from "@/components/layout/Layout";
import { sidebarContents } from "@/components/sidebarNavigation";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ThemeProvider defaultTheme="light" defaultRadius="1em">
          <Layout
            sidebarTitle="HUI"
            sidebarContents={sidebarContents}
            type="fixed"
            position="left"
          >
            {children}
          </Layout>
        </ThemeProvider>
      </body>
    </html>
  );
}
